apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
spec:
  selector:
    matchLabels:
      app: {{ name }}
  replicas: 2 
  template:
    metadata:
      labels:
        app: {{ name }}
    spec:
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
      containers:
      - name: {{ name }}-container
        image: {{ image }}
        ports:
        - containerPort: {{ port }}
          name: "container-port"
        {% if readinessProbePath %}
        readinessProbe:
          httpGet:
            path: {{ readinessProbePath }}
            port: "container-port"
          initialDelaySeconds: 8
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        {% endif %}
        {% if livenessProbePath %}
        livenessProbe:
          httpGet:
            path: {{ livenessProbePath }}
            port: "container-port"
          initialDelaySeconds: 8
          periodSeconds: 10
        {% endif %}
        resources:
          limits:
            cpu: 1
            memory: "1G"
