apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ name }}-ingress
  namespace: {{ namespace }}
spec:
  rules:
  - host: {{ host }}
    http:
      paths:
      - path: {{ path }}
        backend:
          serviceName: {{ name }}-service
          servicePort: {{ port }}
