apiVersion: v1
kind: Service
metadata:
  name: {{ name }}-service
  namespace: {{ namespace }}
spec:
  selector:
    app: {{ name }}
  ports:
  - port: {{ port }}
    targetPort: {{ port }}
    protocol: TCP
  type: ClusterIP
